apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    run: pod2
spec:
  volumes:
    - name: html-storage
      persistentVolumeClaim:
        claimName: my-claim
  containers:
    - name: pod2
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: html-storage
